config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  namespace :admins_backoffice do
    resources :eventos do
      collection do
        get 'inscritos'
      end
    end
    resources :parceiros
  end

  namespace :users_backoffice do
    get 'eventos/evento', :defaults => { :format => :json }
    get 'eventos/programacao', :defaults => { :format => :json }
  end
  root "admins_backoffice/eventos#index"
end

app/models/evento.rb
# == Schema Information
#
# Table name: eventos
#
#  id            :bigint           not null, primary key
#  titulo        :string
#  descricao     :string
#  local         :string
#  data_inicio   :date
#  data_fim      :date
#  codigo        :string
#  admin_id      :bigint
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  data_inicio_s :string
#  data_fim_s    :string
#
class Evento < ApplicationRecord
  belongs_to :admin
  has_many :dias, inverse_of: :evento, dependent: :destroy
  accepts_nested_attributes_for :dias, reject_if: :all_blank, allow_destroy: true

  has_many :evento_parceiros, dependent: :destroy
  has_many :parceiros, through: :evento_parceiros, dependent: :destroy

  has_one_attached :imagem

  after_create :set_codigo

  def set_codigo
    self.codigo = "#{Date.today.year}#{100+id}"
    self.save
  end
end

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
end

app/controllers/admins_backoffice/eventos_controller.rb
class AdminsBackoffice::EventosController < AdminsBackofficeController
  before_action :set_evento, only: [:show, :edit, :update, :destroy]
  before_action :set_combos, only: [:new, :create, :edit, :update]

  # GET /eventos
  # GET /eventos.json
  def index
    @eventos = Evento.where(admin_id: current_admin[:id])
  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
  end

  # GET /eventos/new
  def new
    @evento = Evento.new
  end

  # GET /eventos/1/edit
  def edit
  end

  # POST /eventos
  # POST /eventos.json
  def create
    @evento = Evento.new(evento_params)

    respond_to do |format|
      if @evento.save
        format.html { redirect_to admins_backoffice_eventos_path, notice: t('messages.cadastrado') }
        format.json { render :show, status: :created, location: @evento }
      else
        format.html { render :new }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eventos/1
  # PATCH/PUT /eventos/1.json
  def update
    respond_to do |format|
      if @evento.update(evento_params)
        format.html { redirect_to admins_backoffice_eventos_path, notice: t('messages.alterado') }
        format.json { render :show, status: :ok, location: @evento }
      else
        format.html { render :edit }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento.destroy
    respond_to do |format|
      format.html { redirect_to admins_backoffice_eventos_path, notice: t('messages.deletado') }
      format.json { head :no_content }
    end
  end

  def inscritos

    require "google/cloud/firestore"
    firestore = Google::Cloud::Firestore.new(project_id: "my-event-b8375",credentials: "config/firebase.json")
    table = firestore.collection 'users'
    #table.where('cpf', '==', '06250631127').get.map {|u| u.data[:email] }
    #table.where('cpf', '==', '06250631127').get.count
    #table.get.count
    #
    ## traz dados de um usuário
    #firestore.doc('users/Dv6f3VvRsMRtR3U7StxhbJHM2cl1').get.data
    #
    ## traz os nomes de todos usuarios de uma lista de cpfs
    #table.get.select {|u| ['06250631127'].include? u.data[:cpf] }.map {|u| u.data[:name] }

    # traz inscritos em um determinado evento
    i_eventos = firestore.collection 'inscricoes_evento'
    #binding.pry
    user_ids = i_eventos.where('evento_id', '==', params[:id]).get.map {|i| i.data[:user_id]}.uniq

    #binding.pry
    # traz os nomes de todos usuarios de uma lista de cpfs
    @users = table.get.select {|u| user_ids.include? u.document_id }.map {|u| u.data}



    ## traz inscritos em uma determinada atividade
    #i_atividades = firestore.collection 'inscricoes_atividade'
    #i_atividades.where('atividade_id', '==', '1').get.map {|i| i.data[:user_id]}

  end

  private

  def set_combos
    @parceiros = Parceiro.where(admin_id: current_admin[:id]).map { |p| [p.nome, p.id] }
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_evento
    #@evento = Evento.includes(dias: [:atividades]).find(params[:id])
    @evento = Evento.left_outer_joins(dias: [:atividades]).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def evento_params
    params.require(:evento).permit(:titulo,
                                   :descricao,
                                   :data_inicio_s,
                                   :data_fim_s,
                                   :local,
                                   :codigo,
                                   :admin_id,
                                   :imagem,
                                   parceiro_ids: [],
                                   dias_attributes: [:id, :data_s, :_destroy,
                                                     atividades_attributes: [:id, :titulo, :descricao, :hora_s, :local, :_destroy]])
  end
end

app/controllers/admins_backoffice/parceiros_controller.rb
class AdminsBackoffice::ParceirosController < AdminsBackofficeController
  before_action :set_parceiro, only: [:show, :edit, :update, :destroy]

  # GET /parceiros
  # GET /parceiros.json
  def index
    @parceiros = Parceiro.where admin_id: current_admin[:id]
  end

  # GET /parceiros/1
  # GET /parceiros/1.json
  def show
  end

  # GET /parceiros/new
  def new
    @parceiro = Parceiro.new
  end

  # GET /parceiros/1/edit
  def edit
  end

  # POST /parceiros
  # POST /parceiros.json
  def create
    @parceiro = Parceiro.new(parceiro_params)

    respond_to do |format|
      if @parceiro.save
        format.html { redirect_to admins_backoffice_parceiros_path, notice: 'Parceiro was successfully created.' }
        format.json { render :show, status: :created, location: @parceiro }
      else
        format.html { render :new }
        format.json { render json: @parceiro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parceiros/1
  # PATCH/PUT /parceiros/1.json
  def update
    respond_to do |format|
      if @parceiro.update(parceiro_params)
        format.html { redirect_to admins_backoffice_parceiros_path, notice: 'Parceiro was successfully updated.' }
        format.json { render :show, status: :ok, location: @parceiro }
      else
        format.html { render :edit }
        format.json { render json: @parceiro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parceiros/1
  # DELETE /parceiros/1.json
  def destroy
    @parceiro.destroy
    respond_to do |format|
      format.html { redirect_to admins_backoffice_parceiros_path, notice: 'Parceiro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_parceiro
    @parceiro = Parceiro.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def parceiro_params
    params.require(:parceiro).permit(:nome,
                                     :descricao,
                                     :admin_id,
                                     :imagem,
                                     :tipo)
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
  layout 'admins_backoffice'
  before_action :authenticate_admin!
end

app/controllers/users_backoffice/eventos_controller.rb
class UsersBackoffice::EventosController < UsersBackofficeController
  before_action :set_evento, only: [:evento]

  def evento
  end

  def programacao
    # binding.pry
    @evento = Evento.left_outer_joins(dias: [:atividades]).find(params[:id])
  end

  private

  def set_evento
    if params[:code]
      @evento = Evento.find_by(codigo: params[:code])
    else
    @evento = Evento.find(params[:id])
    end
  end
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/eventos_helper.rb
module AdminsBackoffice::EventosHelper
end

app/helpers/admins_backoffice/parceiros_helper.rb
module AdminsBackoffice::ParceirosHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
end

app/helpers/eventos_helper.rb
# == Schema Information
#
# Table name: eventos
#
#  id            :bigint           not null, primary key
#  titulo        :string
#  descricao     :string
#  local         :string
#  data_inicio   :date
#  data_fim      :date
#  codigo        :string
#  admin_id      :bigint
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  data_inicio_s :string
#  data_fim_s    :string
#
module EventosHelper
end

app/helpers/users_backoffice/eventos_helper.rb
module UsersBackoffice::EventosHelper
end

app/views/admins_backoffice/eventos/_atividades_fields.html.erb
<div class='nested-fields'>

  <div class="x_panel">
    <div class="x_title">
      <h2>Atividade</h2>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <div class="form-group">
        <%= f.label :titulo, class: 'mb-0' %>
        <%= f.text_field :titulo,
                         class: "form-control",
                         placeholder: 'Título', maxlength: 60, size: 60 %>
        <span style="font-style: italic;">(máx 60 caracteres)</span>
      </div>

      <div class="form-group">
        <%= f.label :descricao, class: "mb-0" %>
        <%= f.text_area :descricao,
                        class: "form-control",
                        placeholder: 'Descrição', size: "3x3", maxlength: 250 %>
        <span style="font-style: italic;">(máx 250 caracteres)</span>
      </div>
      
      <div class="row">
        <div class="col-md-12 col-sm-6">
          <div class="form-group">
            <%= f.label :hora_s, 'Horas', class: "mb-0" %>
            <%= f.text_field :hora_s, class: 'form-control time' %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :local, class: "mb-0" %>
        <%= f.text_field :local,
                        class: "form-control",
                        placeholder: 'Local', maxlength: 80, size: 80 %>
        <span style="font-style: italic;">(máx 80 caracteres)</span>
      </div>

      <%= link_to_remove_association "remover atividade", f, {class: 'red', style: 'float: right;'} %>
    </div>
  </div>
</div>

app/views/admins_backoffice/eventos/_dias_fields.html.erb
<div class="x_panel">
  <div class='nested-fields' id="ajax-fields">


    <div class="form-group">
      <%= f.label :data_s, 'Dias', class: 'mb-0' %>
      <%= f.text_field :data_s, class: 'form-control date' %>
    </div>



    <%= f.fields_for :atividades do |atividade| %>
      <%= render 'atividades_fields', :f => atividade %>
    <% end %>
    <div class='links'>
      <%= link_to_add_association 'adicionar atividade', f, :atividades,
                                  {partial: 'atividades_fields',
                                   class: 'btn btn-info btn-sm mt-2 add-atividade'} %>
    </div>

    <%= link_to_remove_association "remover dia", f, {class: 'red', style: 'float: right;'} %>

  </div>
</div>

app/views/admins_backoffice/eventos/_form.html.erb
<div class="row">
  <div class="col-md-12 col-sm-12 ">
    <div class="x_panel">
      <div class="x_title">
        <h2>Dados do evento</h2>
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>

      <div class="x_content">
        <div class="row"></div>
        <%= form_with model: [:admins_backoffice, evento], local: true, class: "form-horizontal form-label-left" do |f| %>
          <div class="form-group">
            <div class="col-md-12 col-sm-6">
              <button type="submit" class="btn btn-success" style="float: right;">Salvar</button>
              <a class="btn btn-danger text-white" href="<%= admins_backoffice_eventos_path %>" style="float: right;">Voltar</a>
            </div>
          </div>

          <% if evento.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(evento.errors.count, "error") %> prohibited this evento from being saved:</h2>

              <ul>
                <% evento.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="row">
            <div class="col-md-6 col-sm-6 ">
              <div class="form-group">
                <%= f.label :imagem, class: 'mb-0' %>
                <%= f.file_field :imagem,
                                 class: "form-control",
                                 placeholder: 'Logo', direct_upload: true %>
              </div>
            </div>

            <div class="col-md-3 col-sm-12 ">
              <div class="form-group">
                <%= f.label :data_inicio_s, 'Data início', class: "mb-0" %>
                <%= f.text_field :data_inicio_s,
                                 class: "form-control date" %>
              </div>
            </div>

            <div class="col-md-3 col-sm-12 ">
              <div class="form-group">
                <%= f.label :data_fim_s, 'Data fim', class: "mb-0" %>
                <%= f.text_field :data_fim_s,
                                 class: "form-control date" %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-6 col-sm-6 ">
              <div class="form-group">
                <%= f.label :titulo, class: "mb-0" %>
                <%= f.text_field :titulo,
                                 class: "form-control",
                                 placeholder: 'Título', maxlength: 60, size: 60 %>
                <span style="font-style: italic;">(máx 60 caracteres)</span>
              </div>
            </div>
            <div class="col-md-6 col-sm-6 ">
              <div class="form-group">
                <%= f.label :local, class: "mb-0" %>
                  <%= f.text_field :local,
                                  class: "form-control",
                                  placeholder: 'Local', maxlength: 50, size: 50 %>
                <span style="font-style: italic;">(máx 50 caracteres)</span>
              </div>
            </div>
          </div>
            <div class="row">
              <div class="col-md-6 col-sm-6">
                <%= f.label :descricao, class: "mb-0" %>
                <%= f.text_area :descricao,
                                class: "form-control",
                                placeholder: 'Descrição', size: "3x4", maxlength: 250 %>
                <span style="font-style: italic;">(máx 250 caracteres)</span>
              </div>

              <div class="col-md-6 col-sm-6">
                <div class="form-group">
                <%= f.label :parceiro_ids, "Parceiros", class: "mb-0" %>
                  <%= f.select :parceiro_ids,
                               options_for_select(@parceiros, evento.parceiro_ids),
                               {},
                               {class: 'select2_multiple form-control', multiple: "multiple"} %>
                </div>
              </div>
            </div>

          <%= f.hidden_field :admin_id, value: current_admin[:id] %>

          <div class="ln_solid"></div>

          <div class="row">
            <div class="col-md-12 col-sd-6">
              <%= f.fields_for :dias do |dia| %>
                <%= render 'dias_fields', :f => dia %>
              <% end %>
              <div class='links'>
                <%= link_to_add_association 'adicionar dia', f, :dias,
                                            {partial: 'dias_fields',
                                             class: 'btn btn-success btn-sm mt-2 add-dia'} %>
              </div>
            </div>
          </div>


          <div class="ln_solid"></div>
          <div class="form-group">
            <div class="col-md-12 col-sm-6">
              <button type="submit" class="btn btn-success" style="float: right;">Salvar</button>
              <a class="btn btn-danger text-white" href="<%= admins_backoffice_eventos_path %>" style="float: right;">Voltar</a>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% content_for :footer_adm do %>
  <script>
      $(document).ready(function () {
          $('.date').mask('00/00/0000');

          $(document).on('click', '.add-dia', function () {
              $('.date').mask('00/00/0000');
          })

          $(document).on('click', '.add-atividade', function () {
              $('.time').mask('00:00');
          })
      });
  </script>
<% end %>

app/views/admins_backoffice/eventos/edit.html.erb
<%= render 'form', evento: @evento %>

app/views/admins_backoffice/eventos/index.html.erb
<div class="col-md-12 col-sm-6  ">
  <div class="x_panel">
    <div class="x_title">
      <h2>Eventos</h2>
      <ul class="nav navbar-right panel_toolbox">
        <li class="houver-link">
          <%= link_to new_admins_backoffice_evento_path, class: 'btn btn-success', style: 'color: white;' do %>
            <i class="fa fa-plus-circle text-white"></i> Novo
          <% end %>
          <!--          <a class="btn btn-success">Success</a>-->
        </li>
      </ul>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">

      <div class="table-responsive">
        <table class="table table-hover">
          <thead>
          <tr>
            <th width="40%">Título</th>
            <th width="25%">Código</th>
            <th width="35%">Ações</th>
          </tr>
          </thead>
          <tbody>
          <% @eventos.each do |evento| %>
            <tr>
              <td width="40%"><%= evento.titulo.truncate(60) %></td>
              <td width="25%"><%= evento.codigo %></td>
              <td width="35%" class="acoes">

                <%= link_to admins_backoffice_evento_path(evento), class: "btn btn-primary btn-xs" do %>
                  <i class="fa fa-folder"></i> Visualizar
                <% end %>
                <%= link_to edit_admins_backoffice_evento_path(evento), class: "btn btn-info btn-xs" do %>
                  <i class="fa fa-pencil"></i> Editar
                <% end %>
                <%= link_to "/admins_backoffice/eventos/#{evento.id}", method: :delete, data: {confirm: 'Você tem certeza?'}, class: "btn btn-danger btn-xs" do %>
                  <i class="fa fa-trash-o"></i> Excluir
                <% end %>
                <%= link_to inscritos_admins_backoffice_eventos_path(id: evento.id), class: "btn btn-secondary btn-xs" do %>
                  <i class="fa fa-folder"></i> Inscritos
                <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>

    </div>
  </div>
</div>

app/views/admins_backoffice/eventos/inscritos.html.erb
<% if @users.empty? %>
<h2>Nenhum inscrito ainda.</h2>
<% else %>
  <div class="x_panel">
    <div class="x_title">
      <h2>Lista de inscritos</h2>
      <ul class="nav navbar-right panel_toolbox">
        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
        </li>
      </ul>
      <div class="clearfix"></div>
    </div>


    <div class="x_content">

      <table class="table table-bordered">
        <thead>
        <tr>
          <th>#</th>
          <th>Nome</th>
          <th>CPF</th>
          <th>email</th>
        </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <th scope="row">1</th>
            <td><%= user[:name] %></td>
            <td><%= user[:cpf] %></td>
            <td><%= user[:email] %></td>
          </tr>
        <% end %>
        </tbody>
      </table>

    </div>


  </div>
<% end %>

app/views/admins_backoffice/eventos/new.html.erb
<%= render 'form', evento: @evento %>

app/views/admins_backoffice/eventos/show.html.erb
<div class="x_panel">
  <div class="x_title">
    <h2><%= @evento.titulo %></h2>
    <ul class="nav navbar-right panel_toolbox">
      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
      </li>
    </ul>
    <div class="clearfix"></div>
  </div>
  <div class="x_content">
    <div class="row">
      <div class="d-flex justify-content-center mb-3 table-responsive" style="float: left; text-align: center">
<!--        <div class="bd-highlight">-->
        <%= image_tag @evento.imagem, style: 'height:150px;width:auto;' %>

      </div>

      <div class="col-md-6">
        <div class="x_panel">
          <p>
            <strong>Descricao:</strong>
            <%= @evento.descricao %>
          </p>

          <p>
            <strong>Local:</strong>
            <%= @evento.local %>
          </p>

          <p>
            <strong>Data inicio:</strong>
            <%= @evento.data_inicio %>
          </p>

          <p>
            <strong>Data fim:</strong>
            <%= @evento.data_fim %>
          </p>

          <p>
            <strong>Codigo:</strong>
            <%= @evento.codigo %>
          </p>

          <p>
            <strong>Admin:</strong>
            <%= @evento.admin.email %>
          </p>


        </div>
      </div>

      <div class="col-md-6">
        <div class="x_panel">
          <p>
            <strong>parceiros:</strong> <br>
            <% @evento.parceiros.each do |parceiro| %>
              <span style="margin-left: 5px"><%= "• #{parceiro.nome}" %></span> <br>
            <% end %>
          </p>


        </div>
      </div>

      <div class="col-md-12">
        <!--        <div class="x_panel">-->
        <div class="d-flex justify-content-center">
          <div><h6>Progração</h6></div>
        </div>

        <% @evento.dias.each do |dia| %>
          <div class="row">
            <div class="x_panel">
              <div class="col-md-12">
                <h2>
                  <%= dia.data_s %>
                  <a class="collapse-link pointer-event" style="float: right; cursor: pointer;"><i class="fa fa-chevron-up"></i></a>
                </h2>
              </div>
              <div class="x_content">
                <% dia.atividades.each do |atv| %>
                  <div class="col-md-4">
                    <div class="x_panel">
                      <strong>titulo </strong> <%= atv.titulo %> <br>
                      <strong>hora </strong><%= atv.hora_s %> <br>
                      <strong>descrição </strong><%= atv.descricao %> <br>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>


          </div>
        <% end %>
      </div>
    </div>
    <!--    </div>-->

  </div>
</div>