config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  namespace :admins_backoffice do
    resources :eventos do
      collection do
        get 'inscritos'
      end
    end
    resources :parceiros
  end

  namespace :users_backoffice do
    get 'eventos/evento', :defaults => { :format => :json }
    get 'eventos/programacao', :defaults => { :format => :json }
  end
  root "admins_backoffice/eventos#index"
end

app/models/parceiro.rb
# == Schema Information
#
# Table name: parceiros
#
#  id         :bigint           not null, primary key
#  nome       :string
#  imagens    :json
#  descricao  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  admin_id   :bigint
#  img_link   :string
#  tipo       :string
#
class Parceiro < ApplicationRecord
  has_many :evento_parceiros, dependent: :destroy
  has_many :eventos, through: :evento_parceiros, dependent: :destroy

  belongs_to :admin

  extend Enumerize
  extend ActiveModel::Naming
  enumerize :tipo, in: %w(patrocinador apoiador organizador), i18n_scope: "tipo_parceiro_values", predicates: true

  #mount_uploaders :imagens, ImageUploader

  has_one_attached :imagem
end

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
end

app/controllers/admins_backoffice/eventos_controller.rb
class AdminsBackoffice::EventosController < AdminsBackofficeController
  before_action :set_evento, only: [:show, :edit, :update, :destroy]
  before_action :set_combos, only: [:new, :create, :edit, :update]

  # GET /eventos
  # GET /eventos.json
  def index
    @eventos = Evento.where(admin_id: current_admin[:id])
  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
  end

  # GET /eventos/new
  def new
    @evento = Evento.new
  end

  # GET /eventos/1/edit
  def edit
  end

  # POST /eventos
  # POST /eventos.json
  def create
    @evento = Evento.new(evento_params)

    respond_to do |format|
      if @evento.save
        format.html { redirect_to admins_backoffice_eventos_path, notice: t('messages.cadastrado') }
        format.json { render :show, status: :created, location: @evento }
      else
        format.html { render :new }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eventos/1
  # PATCH/PUT /eventos/1.json
  def update
    respond_to do |format|
      if @evento.update(evento_params)
        format.html { redirect_to admins_backoffice_eventos_path, notice: t('messages.alterado') }
        format.json { render :show, status: :ok, location: @evento }
      else
        format.html { render :edit }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento.destroy
    respond_to do |format|
      format.html { redirect_to admins_backoffice_eventos_path, notice: t('messages.deletado') }
      format.json { head :no_content }
    end
  end

  def inscritos

    require "google/cloud/firestore"
    firestore = Google::Cloud::Firestore.new(project_id: "my-event-b8375",credentials: "config/firebase.json")
    table = firestore.collection 'users'
    #table.where('cpf', '==', '06250631127').get.map {|u| u.data[:email] }
    #table.where('cpf', '==', '06250631127').get.count
    #table.get.count
    #
    ## traz dados de um usuário
    #firestore.doc('users/Dv6f3VvRsMRtR3U7StxhbJHM2cl1').get.data
    #
    ## traz os nomes de todos usuarios de uma lista de cpfs
    #table.get.select {|u| ['06250631127'].include? u.data[:cpf] }.map {|u| u.data[:name] }

    # traz inscritos em um determinado evento
    i_eventos = firestore.collection 'inscricoes_evento'
    #binding.pry
    user_ids = i_eventos.where('evento_id', '==', params[:id]).get.map {|i| i.data[:user_id]}.uniq

    #binding.pry
    # traz os nomes de todos usuarios de uma lista de cpfs
    @users = table.get.select {|u| user_ids.include? u.document_id }.map {|u| u.data}



    ## traz inscritos em uma determinada atividade
    #i_atividades = firestore.collection 'inscricoes_atividade'
    #i_atividades.where('atividade_id', '==', '1').get.map {|i| i.data[:user_id]}

  end

  private

  def set_combos
    @parceiros = Parceiro.where(admin_id: current_admin[:id]).map { |p| [p.nome, p.id] }
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_evento
    #@evento = Evento.includes(dias: [:atividades]).find(params[:id])
    @evento = Evento.left_outer_joins(dias: [:atividades]).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def evento_params
    params.require(:evento).permit(:titulo,
                                   :descricao,
                                   :data_inicio_s,
                                   :data_fim_s,
                                   :local,
                                   :codigo,
                                   :admin_id,
                                   :imagem,
                                   parceiro_ids: [],
                                   dias_attributes: [:id, :data_s, :_destroy,
                                                     atividades_attributes: [:id, :titulo, :descricao, :hora_s, :local, :_destroy]])
  end
end

app/controllers/admins_backoffice/parceiros_controller.rb
class AdminsBackoffice::ParceirosController < AdminsBackofficeController
  before_action :set_parceiro, only: [:show, :edit, :update, :destroy]

  # GET /parceiros
  # GET /parceiros.json
  def index
    @parceiros = Parceiro.where admin_id: current_admin[:id]
  end

  # GET /parceiros/1
  # GET /parceiros/1.json
  def show
  end

  # GET /parceiros/new
  def new
    @parceiro = Parceiro.new
  end

  # GET /parceiros/1/edit
  def edit
  end

  # POST /parceiros
  # POST /parceiros.json
  def create
    @parceiro = Parceiro.new(parceiro_params)

    respond_to do |format|
      if @parceiro.save
        format.html { redirect_to admins_backoffice_parceiros_path, notice: 'Parceiro was successfully created.' }
        format.json { render :show, status: :created, location: @parceiro }
      else
        format.html { render :new }
        format.json { render json: @parceiro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parceiros/1
  # PATCH/PUT /parceiros/1.json
  def update
    respond_to do |format|
      if @parceiro.update(parceiro_params)
        format.html { redirect_to admins_backoffice_parceiros_path, notice: 'Parceiro was successfully updated.' }
        format.json { render :show, status: :ok, location: @parceiro }
      else
        format.html { render :edit }
        format.json { render json: @parceiro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parceiros/1
  # DELETE /parceiros/1.json
  def destroy
    @parceiro.destroy
    respond_to do |format|
      format.html { redirect_to admins_backoffice_parceiros_path, notice: 'Parceiro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_parceiro
    @parceiro = Parceiro.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def parceiro_params
    params.require(:parceiro).permit(:nome,
                                     :descricao,
                                     :admin_id,
                                     :imagem,
                                     :tipo)
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
  layout 'admins_backoffice'
  before_action :authenticate_admin!
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/eventos_helper.rb
module AdminsBackoffice::EventosHelper
end

app/helpers/admins_backoffice/parceiros_helper.rb
module AdminsBackoffice::ParceirosHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
end

app/views/admins_backoffice/parceiros/_form.html.erb
<div class="row">
  <div class="col-md-12 col-sm-12 ">
    <div class="x_panel">
      <div class="x_title">
        <ul class="nav navbar-right panel_toolbox">
          <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
          </li>
        </ul>
        <div class="clearfix"></div>
      </div>

      <div class="x_content">
        <br>
        <%= form_with model: [:admins_backoffice, parceiro], local: true, class: "form-horizontal form-label-left" do |f| %>

          <% if parceiro.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(parceiro.errors.count, "error") %> prohibited this parceiro from being saved:</h2>

              <ul>
                <% parceiro.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <%= f.hidden_field :admin_id, value: current_admin[:id] %>

          <div class="item form-group">
            <%= f.label :nome, class: "col-form-label col-md-3 col-sm-3 label-align" %>
            <div class="col-md-6 col-sm-6 ">
              <%= f.text_field :nome,
                               class: "form-control",
                               placeholder: 'Nome' %>
            </div>
          </div>

          <div class="item form-group">
            <%= f.label :descricao, class: "col-form-label col-md-3 col-sm-3 label-align" %>
            <div class="col-md-6 col-sm-6 ">
              <%= f.text_area :descricao,
                              class: "form-control",
                              placeholder: 'Descrição' %>
            </div>
          </div>

          <div class="item form-group">
            <%= f.label :imagem, class: "col-form-label col-md-3 col-sm-3 label-align" %>
            <div class="col-md-6 col-sm-6 ">
              <%= f.file_field :imagem,
                               class: "form-control",
                               placeholder: 'Logo', direct_upload: true %>
            </div>
          </div>

          <div class="item form-group">
            <%= f.label :tipo, class: "col-form-label col-md-3 col-sm-3 label-align" %>
            <div class="col-md-6 col-sm-6 ">
              <%#= f.text_field :img_link, placeholder: 'http://imga.com' %>

              <%= f.select :tipo,
                                 Parceiro.tipo.options,
                                 {},
                                 {class: 'form-control'} %>
            </div>
          </div>

          <div class="ln_solid"></div>
          <div class="item form-group">
            <div class="col-md-6 col-sm-6 offset-3">
              <button type="submit" class="btn btn-success" style="float: right;">Salvar</button>
              <a class="btn btn-danger text-white" href="<%= admins_backoffice_parceiros_path %>" style="float: right;">Voltar</a>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admins_backoffice/parceiros/edit.html.erb
<h2>Editando <%= @parceiro.nome %></h2>

<%= render 'form', parceiro: @parceiro %>

app/views/admins_backoffice/parceiros/index.html.erb
<div class="col-md-12 col-sm-6  ">
  <div class="x_panel">
    <div class="x_title">
      <h2>Parceiros</h2>
      <ul class="nav navbar-right panel_toolbox">
        <li class="houver-link">
          <%= link_to new_admins_backoffice_parceiro_path, class: 'btn btn-success', style: 'color: white;' do %>
            <i class="fa fa-plus-circle text-white"></i> Novo
          <% end %>
          <!--          <a class="btn btn-success">Success</a>-->
        </li>
      </ul>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">

      <div class="table-responsive">
        <table class="table table-hover">
          <thead>
          <tr>
            <th width="40%">Nome</th>
            <th width="30%">Imagens</th>
            <th width="30%">Ações</th>
          </tr>
          </thead>
          <tbody>
          <% @parceiros.each do |parceiro| %>
            <tr>
              <td width="40%"><%= parceiro.nome %></td>
              <td width="30%">
                  <a href="#" onclick='window.open("<%= url_for(parceiro.imagem) %>");return false;'>
                    <%= image_tag url_for(parceiro.imagem), class: 'img-icon-small' %>
                  </a>
              </td>
              <td width="30%" class="acoes">
                <%= link_to admins_backoffice_parceiro_path(parceiro), class: "btn btn-primary btn-xs" do %>
                  <i class="fa fa-folder"></i> Visualizar
                  <% end %>
                <%= link_to edit_admins_backoffice_parceiro_path(parceiro), class:"btn btn-info btn-xs" do %>
                  <i class="fa fa-pencil"></i> Editar
                  <% end %>
                <%= link_to "/admins_backoffice/parceiros/#{parceiro.id}", method: :delete, data: {confirm: 'Você tem certeza?'}, class:"btn btn-danger btn-xs" do %>
                  <i class="fa fa-trash-o"></i> Excluir
                  <% end %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>

    </div>
  </div>
</div>

app/views/admins_backoffice/parceiros/new.html.erb
<h2>Novo Parceiro</h2>

<%= render 'form', parceiro: @parceiro %>

app/views/admins_backoffice/parceiros/show.html.erb
<div class="x_panel">
  <div class="d-flex justify-content-center bd-highlight mb-3">

    <div class="p-4 bd-highlight card">
      <%= image_tag @parceiro.imagem, style: 'height:90px;width:auto;' %>
      <br>

      <p>

        <strong>Nome:</strong>
        <%= @parceiro.nome %>
      </p>
      <p>

        <strong>Descrição:</strong>
        <%= @parceiro.descricao %>
      </p>

      <p>

        <strong>Tipo:</strong>
        <%= @parceiro.tipo_text %>
      </p>
    </div>
  </div>
    <div class="d-flex justify-content-center bd-highlight">
      <div class="bd-highlight">
        <a class="btn btn-danger text-white" href="<%= admins_backoffice_parceiros_path %>" style="float: right;">Voltar</a>
      </div>
      <div class="bd-highlight">
        <%= link_to edit_admins_backoffice_parceiro_path(@parceiro), class:"btn btn-info btn-xs" do %>
          <i class="fa fa-pencil"></i> Editar
        <% end %>
      </div>
    </div>
</div>