config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  namespace :admins_backoffice do
    resources :eventos do
      collection do
        get 'inscritos'
      end
    end
    resources :parceiros
  end

  namespace :users_backoffice do
    get 'eventos/evento', :defaults => { :format => :json }
    get 'eventos/programacao', :defaults => { :format => :json }
  end
  root "admins_backoffice/eventos#index"
end

app/models/admin.rb
# == Schema Information
#
# Table name: admins
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class Admin < ApplicationRecord
  has_many :eventos
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/atividade.rb
# == Schema Information
#
# Table name: atividades
#
#  id         :bigint           not null, primary key
#  titulo     :string
#  descricao  :string
#  hora       :time
#  dia_id     :bigint
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  hora_s     :string
#
class Atividade < ApplicationRecord
  belongs_to :dia
end

app/models/dia.rb
# == Schema Information
#
# Table name: dias
#
#  id         :bigint           not null, primary key
#  data       :date
#  evento_id  :bigint
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  data_s     :string
#
class Dia < ApplicationRecord
  belongs_to :evento
  has_many :atividades, inverse_of: :dia, dependent: :destroy
  accepts_nested_attributes_for :atividades, reject_if: :all_blank, allow_destroy: true
end

app/models/evento.rb
# == Schema Information
#
# Table name: eventos
#
#  id            :bigint           not null, primary key
#  titulo        :string
#  descricao     :string
#  local         :string
#  data_inicio   :date
#  data_fim      :date
#  codigo        :string
#  admin_id      :bigint
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  data_inicio_s :string
#  data_fim_s    :string
#
class Evento < ApplicationRecord
  belongs_to :admin
  has_many :dias, inverse_of: :evento, dependent: :destroy
  accepts_nested_attributes_for :dias, reject_if: :all_blank, allow_destroy: true

  has_many :evento_parceiros, dependent: :destroy
  has_many :parceiros, through: :evento_parceiros, dependent: :destroy

  has_one_attached :imagem

  after_create :set_codigo

  def set_codigo
    self.codigo = "#{Date.today.year}#{100+id}"
    self.save
  end
end

app/models/evento_parceiro.rb
# == Schema Information
#
# Table name: evento_parceiros
#
#  id          :bigint           not null, primary key
#  evento_id   :bigint
#  parceiro_id :bigint
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class EventoParceiro < ApplicationRecord
  belongs_to :evento
  belongs_to :parceiro
end

app/models/parceiro.rb
# == Schema Information
#
# Table name: parceiros
#
#  id         :bigint           not null, primary key
#  nome       :string
#  imagens    :json
#  descricao  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  admin_id   :bigint
#  img_link   :string
#  tipo       :string
#
class Parceiro < ApplicationRecord
  has_many :evento_parceiros, dependent: :destroy
  has_many :eventos, through: :evento_parceiros, dependent: :destroy

  belongs_to :admin

  extend Enumerize
  extend ActiveModel::Naming
  enumerize :tipo, in: %w(patrocinador apoiador organizador), i18n_scope: "tipo_parceiro_values", predicates: true

  #mount_uploaders :imagens, ImageUploader

  has_one_attached :imagem
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
  layout 'admins_backoffice'
  before_action :authenticate_admin!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource

  protected

  def layout_by_resource
    if devise_controller? && resource_class == Admin
      "admin_devise"
    end
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
end

app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
  layout 'users_backoffice'
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/eventos_helper.rb
module AdminsBackoffice::EventosHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
end

app/helpers/admins_helper.rb
# == Schema Information
#
# Table name: admins
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/eventos_helper.rb
# == Schema Information
#
# Table name: eventos
#
#  id            :bigint           not null, primary key
#  titulo        :string
#  descricao     :string
#  local         :string
#  data_inicio   :date
#  data_fim      :date
#  codigo        :string
#  admin_id      :bigint
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  data_inicio_s :string
#  data_fim_s    :string
#
module EventosHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_backoffice/eventos_helper.rb
module UsersBackoffice::EventosHelper
end

app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/admin_devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Meta, title, CSS, favicons, etc. -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>MyEvent</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'admin_devise', media: 'all', 'data-turbolinks-track': 'reload' %>

</head>

<body class="login">

<%= yield %>

</body>

<%= javascript_include_tag 'admin_devise.js', 'data-turbolinks-track': 'reload' %>

<%# unless resource.errors.empty? %>
  <%# resource.errors.full_messages.each do |msg| %>
    <%#= javascript_tag do %>
<!--      $.bootstrapGrowl('<%#= msg %>', {-->
<!--      type: 'danger', // (null, 'info', 'danger', 'success')-->
<!--      align: 'right', // ('left', 'right', or 'center')-->
<!--      allow_dismiss: true, // If true then will display a cross to close the popup.-->
<!--      stackup_spacing: 10 // spacing between consecutively stacked growls.-->
<!--      });-->
    <%# end %>
  <%# end %>
<%# end %>

<% if flash %>
  <% flash.each do |key, value| %>
    <%= javascript_tag do %>
      $.bootstrapGrowl('<%= value %>', {
      type: 'danger', // (null, 'info', 'danger', 'success')
      align: 'right', // ('left', 'right', or 'center')
      allow_dismiss: true, // If true then will display a cross to close the popup.
      stackup_spacing: 10 // spacing between consecutively stacked growls.
      });
    <% end %>
  <% end %>
<% end %>
</html>

app/views/layouts/admins.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Meta, title, CSS, favicons, etc. -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>MyEvent</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'admins', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>


<body class="nav-md">
<div class="container body">
  <div class="main_container">
    <div class="col-md-3 left_col menu_fixed">
      <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
          <a href="/" class="site_title"><i class="fa fa-bullhorn"></i> <span> My Event </span></a>
        </div>

        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile clearfix">
          <div class="profile_pic">
            <%= image_tag 'img.jpg', alt: "...", class: "img-circle profile_img" %>
          </div>
          <div class="profile_info">
            <span>Welcome,</span>
            <h2><%= current_admin[:email] %></h2>
          </div>
        </div>
        <!-- /menu profile quick info -->

        <br/>

        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
          <div class="menu_section">
            <ul class="nav side-menu">
              <li>
                <a href="<%= admins_backoffice_eventos_path %>"><i class="fa fa-calendar"></i>Eventos</a>
              </li>
              <li>
                <a href="<%= admins_backoffice_parceiros_path %>"><i class="fa fa-users"></i>Parceiros</a>
              </li>
            </ul>
          </div>
        </div>
        <!-- /sidebar menu -->

        <!-- /menu footer buttons -->
        <div class="sidebar-footer hidden-small">
          <a data-toggle="tooltip" data-placement="top" title="Settings">
            <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
          </a>
          <a data-toggle="tooltip" data-placement="top" title="FullScreen">
            <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
          </a>
          <a data-toggle="tooltip" data-placement="top" title="Lock">
            <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
          </a>
          <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
          </a>
        </div>
        <!-- /menu footer buttons -->
      </div>
    </div>

    <!-- top navigation -->
    <div class="top_nav">
      <div class="nav_menu">
        <div class="nav toggle">
          <a id="menu_toggle"><i class="fa fa-bars"></i></a>
        </div>
        <nav class="nav navbar-nav">
          <ul class=" navbar-right">
            <li class="nav-item dropdown open" style="padding-left: 15px;">
              <a href="javascript:;" class="user-profile dropdown-toggle" aria-haspopup="true" id="navbarDropdown" data-toggle="dropdown" aria-expanded="false">
                <%= image_tag 'img.jpg' %>
                <%= current_admin[:email] %>
              </a>
              <div class="dropdown-menu dropdown-usermenu pull-right" aria-labelledby="navbarDropdown">
                <%= link_to '#', class: 'dropdown-item' do %>
                  <i class="fa fa-user pull-right"></i> Dados do perfil
                <% end %>
                <%= link_to destroy_admin_session_path, :method => :delete, class: 'dropdown-item' do %>
                  <i class="fa fa-sign-out pull-right"></i> Sair
                <% end %>
              </div>
            </li>

          </ul>
        </nav>
      </div>
    </div>
    <!-- /top navigation -->

    <!-- page content -->
    <div class="right_col" role="main">
      <%= yield %>
    </div>
    <!-- /page content -->

    <!-- footer content -->
    <footer>
      <div class="pull-right">
        Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
      </div>
      <div class="clearfix"></div>
    </footer>
    <!-- /footer content -->
  </div>
</div>
<%= javascript_include_tag 'admins', 'data-turbolinks-track': 'false' %>

<% if notice %>
  <%= javascript_tag do %>
    $.bootstrapGrowl('<%= notice %>', {
    type: 'success', // (null, 'info', 'danger', 'success')
    align: 'right', // ('left', 'right', or 'center')
    allow_dismiss: true, // If true then will display a cross to close the popup.
    stackup_spacing: 10 // spacing between consecutively stacked growls.
    });
  <% end %>
<% end %>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>
<%= yield(:footer_adm) %>
</body>
</html>

app/views/layouts/admins_backoffice.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Meta, title, CSS, favicons, etc. -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>MyEvent</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'admins_backoffice', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>


<body class="nav-md">
<div class="container body">
  <div class="main_container">
    <div class="col-md-3 left_col menu_fixed">
      <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
          <a href="/" class="site_title"><i class="fa fa-bullhorn"></i> <span> My Event </span></a>
        </div>

        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile clearfix">
          <div class="profile_pic">
            <%= image_tag 'img.jpg', alt: "...", class: "img-circle profile_img" %>
          </div>
          <div class="profile_info">
            <span>Welcome,</span>
            <h2><%= current_admin[:email] %></h2>
          </div>
        </div>
        <!-- /menu profile quick info -->

        <br/>

        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
          <div class="menu_section">
            <ul class="nav side-menu">
              <li>
                <a href="<%= admins_backoffice_eventos_path %>"><i class="fa fa-calendar"></i>Eventos</a>
              </li>
              <li>
                <a href="<%= admins_backoffice_parceiros_path %>"><i class="fa fa-users"></i>Parceiros</a>
              </li>
            </ul>
          </div>
        </div>
        <!-- /sidebar menu -->
      </div>
    </div>

    <!-- top navigation -->
    <div class="top_nav">
      <div class="nav_menu">
        <div class="nav toggle">
          <a id="menu_toggle"><i class="fa fa-bars"></i></a>
        </div>
        <nav class="nav navbar-nav">
          <ul class=" navbar-right">
            <li class="nav-item dropdown open" style="padding-left: 15px;">
              <a href="javascript:;" class="user-profile dropdown-toggle" aria-haspopup="true" id="navbarDropdown" data-toggle="dropdown" aria-expanded="false">
                <%= image_tag 'img.jpg' %>
                <%= current_admin[:email] %>
              </a>
              <div class="dropdown-menu dropdown-usermenu pull-right" aria-labelledby="navbarDropdown">
                <%#= link_to '#', class: 'dropdown-item' do %>
<!--                  <i class="fa fa-user pull-right"></i> Dados do perfil-->
                <%# end %>
                <%= link_to destroy_admin_session_path, :method => :delete, class: 'dropdown-item' do %>
                  <i class="fa fa-sign-out pull-right"></i> Sair
                <% end %>
              </div>
            </li>

          </ul>
        </nav>
      </div>
    </div>
    <!-- /top navigation -->

    <!-- page content -->
    <div class="right_col" role="main">
      <%= yield %>
    </div>
    <!-- /page content -->

    <!-- footer content -->
    <footer>
      <div class="pull-right">
        Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
      </div>
      <div class="clearfix"></div>
    </footer>
    <!-- /footer content -->
  </div>
</div>
<%= javascript_include_tag 'admins_backoffice', 'data-turbolinks-track': 'false' %>

<% if notice %>
  <%= javascript_tag do %>
    $.bootstrapGrowl('<%= notice %>', {
    type: 'success', // (null, 'info', 'danger', 'success')
    align: 'right', // ('left', 'right', or 'center')
    allow_dismiss: true, // If true then will display a cross to close the popup.
    stackup_spacing: 10 // spacing between consecutively stacked growls.
    });
  <% end %>
<% end %>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>
<%= yield(:footer_adm) %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyEvent</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= yield %>
</body>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</html>

app/views/layouts/users_backoffice.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyEvent</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<h1>LAYOUT USER BACKOFFICE</h1>
<%= yield %>
</body>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</html>